### ISSUE TITLE
Latest version 1.1.31 needs Node.js 14.17 

### ISSUE THREAD

**Issue by dragosde** [arachnetech/homebridge-mqttthing#479] opened 2021-09-26 15:22 UTC
I upgraded recently the plugin to the newest version 1.1.31

After reloading homebridge I get this error in the homebridge log:

9/26/2021, 11:09:56] ERROR LOADING PLUGIN homebridge-mqttthing:
[9/26/2021, 11:09:56] /usr/lib/node_modules/homebridge-mqttthing/index.js:1282
                        let data = message?.toString() ?? '';
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Plugin.load (/usr/lib/node_modules/homebridge/src/plugin.ts:187:27)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:126:16
    at Map.forEach (<anonymous>)
[9/26/2021, 11:09:56] ====================

Reverting to the previous version 1.1.30 restores functionality.

I am a layman, don't know much about coding, let me know if you need more info.

**Comment by arachnetech** [comment] 2021-09-26 15:29
Thanks for letting me know. What version of Node.js are you running? You should be able to find out with `node --version`

**Comment by dragosde** [comment] 2021-09-26 15:34
As a good developer, you are on to something. :) 
My node version is 12.22. *showing right in the homebridge UI x
Must be the reason. 
I wonder why I didn't upgrade before. I have to check some notes as it may be a good reason for that.

**Comment by arachnetech** [comment] 2021-09-26 15:34
The issue is the use of the nullish coalescing operator in a pull request which was submitted to mqttthing. This relatively recent JavaScript feature requires Node.js 14, I believe.

**Comment by arachnetech** [comment] 2021-09-26 15:35
If you are able to upgrade to Node.js 14, that would be great. I think that's the recommended version of Homebridge now. I might rewrite the problem line of code to be compatible with Node.js 12 anyway.

**Comment by dragosde** [comment] 2021-09-26 15:49
I may upgrade as another plugin, the Hue also complains about the version. I believe I fell behind with the upgrades, need to keep up. I will report back.
Thanks again

**Comment by dragosde** [comment] 2021-09-26 16:27
Yeap, upgraded Node.js to 14.17 and then upgraded the plugin to the latest version.
All seems well.
Changed the issue title, maybe someone will have the same issue.
Please close the issue.
Thanks again for pointing me in the right direction.

**Comment by rbswift** [comment] 2021-10-04 11:14
interestingly I have the same problem but it manifested quite a while after I updated which took me by surprise. Thanks for saving me a lot of troubleshooting

**Comment by arachnetech** [comment] 2021-11-28 20:29
I've moved properly to requiring Node.js 14 now, so closing this issue.

**Closed by arachnetech** 2021-11-28 20:29 UTC

**Comment by Rahulsharma0810** [comment] 2022-09-23 12:43
```
[9/23/2022, 6:12:41 PM] The plugin "homebridge-mqttthing" requires Node.js version of ^14.18.0 || ^16.10.0 which does not satisfy the current Node.js version of v18.0.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
```
