### ISSUE TITLE
brightness on lightbulb does not work (solved)

### ISSUE THREAD

**Issue by dezral** [arachnetech/homebridge-mqttthing#167] opened 2019-11-04 13:02 UTC
Im trying to get a shelly dimmer/RGBW2/bulb to be able to dimmer from homekit..

but i cant get it to start homebridge with this config.json with this "setBrightness"

```
{
      "accessory": "mqttthing",
      "type": "lightbulb",
      "name": "loft lys",
      "topics": {
        "getOn": "shellies/shellydimmer-xxxxxx/light/0",
        "setOn": "shellies/shellydimmer-xxxxxx/light/0/command"
                },

        "getBrightness":{ 
                "topic": "shellies/shellydimmer-xxxxxx/light/0/status",
                "apply": "return JSON.parse(message.brightness);"
                        },

        "setBrightness":{
                "topic": "shellies/shellydimmer-xxxxxx/light/0/set",
                "apply": "return JSON.stringify("{\"brightness\": " + message + "}");"
                        },

      "onValue":  "on",
      "offValue": "off",
      "logMqtt": true
    }
```

the MQTT output is:
shellies/shellydimmer-xxxxxx/light/0/command off
shellies/shellydimmer-xxxxxx/light/0 off
shellies/shellydimmer-xxxxxx/light/0/status `{"ison":false,"mode":"white","brightness":64}`

and it takes json as a input like so:
`{\"brightness\":64}`
if i just remove "`"apply": "return JSON.stringify("{\"brightness\": " + message + "}");"`" from setBrightness it works fine..

what am i doing wrong?

**Comment by tobekas** [comment] 2019-11-09 22:38
You have to escape all your " in the apply string with \"

**Comment by dezral** [comment] 2019-11-14 11:30
great , that did it regarding starting homebridge ;-).

but i can't get homekit to show it as a dimmable bulb, only on/off

and the topic is correct and mqtt debug is true.. i only get this :
```
[11/14/2019, 12:16:47 PM] [shelly dimmer] Publishing MQTT: shellies/shellydimmer-XXXXXX/light/0/command = on
[11/14/2019, 12:16:47 PM] [shelly dimmer] Received MQTT: shellies/shellydimmer-XXXXXX/light/0 = on
[11/14/2019, 12:16:49 PM] [shelly dimmer] Publishing MQTT: shellies/shellydimmer-XXXXXX/light/0/command = off
[11/14/2019, 12:16:49 PM] [shelly dimmer] Received MQTT: shellies/shellydimmer-XXXXXX/light/0 = off
```
have try'd deleting the bulb and renaming it..

current config is this:
```
{
      "accessory": "mqttthing",
      "type": "lightbulb",
      "name": "dimmer",
      "onValue":  "on",
      "offValue": "off",
      "topics": {
        "getOnline": "shellies/shellydimmer-XXXXXX/online",
        "getOn": "shellies/shellydimmer-XXXXXX/light/0",
        "setOn": "shellies/shellydimmer-XXXXXX/light/0/command"
                },

        "getBrightness":{
                "topic": "shellies/shellydimmer-XXXXXX/light/0/status",
                "apply": "return JSON.parse(message).brightness"
                        },

        "setBrightness":{
                "topic": "shellies/shellydimmer-XXXXXX/light/0/set",
                "apply": "return JSON.stringify(\"{\"brightness\": message }\")"
                        },
      "logMqtt": true
    },

```
![Skærmbillede 2019-11-14 kl  12 28 44](https://user-images.githubusercontent.com/4703712/68853532-7a236a80-06da-11ea-8378-a6956b3979a2.png)

**Comment by tobekas** [comment] 2019-11-14 21:42
Just try
`"apply": "return JSON.stringify({brightness: message});"`

There are some examples for this apply feature in the wiki. Maybe this will help

**Comment by dezral** [comment] 2019-11-15 09:00
still just on/off.. and it does not seem to read/get any brightness data in homebridge that is published.

**Comment by tobekas** [comment] 2019-11-15 21:43
Ah. The problem is that your brightness topics are not structured under "topics".
Your closing } is at the wrong position

**Comment by dezral** [comment] 2019-11-17 09:25
you are so right.. works now. will publish the final best config for shelly dimmer/rgbw2 and bulb when i think its worthy

**Comment by mientki** [comment] 2019-12-04 22:49
Can You show your config?

**Closed** 2020-04-05 14:56 UTC

**Comment by serbasan** [comment] 2020-08-15 22:28
Idem here. Can You show your config?

**Comment by dezral** [comment] 2020-08-16 04:05
```
{
      "accessory": "mqttthing",
      "type": "lightbulb",
      "name": "shelly dimmer",
      "onValue":  "on",
      "offValue": "off",
      "logMqtt": true,
      "topics": {
        "getOn":{
        "topic": "shellies/shellydimmer-XXXXXX/light/0/status",
        "apply": "if(JSON.parse(message).ison === true ) { return \"on\"; } else{ return \"off\"; }"
        },
        "setOn": "shellies/shellydimmer-XXXXXX/light/0/command",
        "getBrightness":{
                "topic": "shellies/shellydimmer-XXXXXX/light/0/status",
                "apply": "return JSON.parse(message).brightness;"
                        },
        "setBrightness":{
                "topic": "shellies/shellydimmer-XXXXXX/light/0/set",
                "apply": "return JSON.stringify({brightness: message});"
                        }
    }
},
```


```
{
    "accessory": "mqttthing",
    "type": "lightbulb",
    "name": "Shelly RGBW2 1",
    "logMqtt": true,
    "topics":
    {
        "getOn": "shellies/shellyrgbw2-XXXXXX/color/0",
        "setOn": "shellies/shellyrgbw2-XXXXXX/color/0/command",
        "getRGBW": {
                "topic": "shellies/shellyrgbw2-XXXXXX/color/0/status",
                "apply": "if(JSON.parse(message).mode === \"color\"){ return JSON.parse(message).red + \",\" + JSON.parse(message).green + \",\" + JSON.parse(message).blue + \",\" + JSON.parse(message).white;}"
                  },

        "setRGBW":{
                "topic": "shellies/shellyrgbw2-XXXXXX/color/0/set",
                "apply": "var end = message.split(\",\"); return JSON.stringify({red: end[0],green: end[1],blue: end[2],white: end[3]});"
                }

   },

    "onValue": "on",
    "offValue": "off"
},

```

**Comment by serbasan** [comment] 2020-08-16 06:34
Thank you, tested and working. You have saved me some work time

**Comment by vskal** [comment] 2021-02-09 23:12
Thank you for the config.
Using it for a Shelly Duo bulb.
I can now control on/off and I can see when the color changes in homekit.
BUT
Still missing brightness and color control from homekit to device.
Here is my config:

    "accessories": [
        {
            "type": "lightbulb",
            "name": "shellyduo",
            "mqttOptions": {
                "keepalive": 30
            },
            "mqttPubOptions": {
                "retain": true
            },
            "logMqtt": true,
            "topics": {
                "getOnline": "shellies/shellycolorbulb-XXXXXXXXXXX/color/0/status",
                "getRGBW": {
                    "topic": "shellies/shellycolorbulb-XXXXXXXXXXXX/color/0/status",
                    "apply": "if(JSON.parse(message).mode === \"color\"){ return JSON.parse(message).red + \",\" + JSON.parse(message).green + \",\" + JSON.parse(message).blue + \",\" + JSON.parse(message).white;}"
                },
                "setRGBW": {
                    "topic": "shellies/shellycolorbulb-XXXXXXXXXXXX/color/0/set",
                    "apply": "var end = message.split(\",\"); return JSON.stringify({red: end[0],green: end[1],blue: end[2],white: end[3]});"
                },
                "getOn": "shellies/shellycolorbulb-XXXXXXXXXXX/color/0",
                "setOn": "shellies/shellycolorbulb-XXXXXXXXXXX/color/0/command",
                "getBrightness": {
                    "topic": "shellies/shellycolorbulb-XXXXXXXXXXX/color/0/status",
                    "apply": "return JSON.parse(message).brightness;"
                },
                "setBrightness": {
                    "topic": "shellies/shellycolorbulb-XXXXXXXXXX/color/0/set",
                    "apply": "return JSON.stringify({brightness: message});"
                }
            },
            "confirmationPeriodms": 1000,
            "retryLimit": 5,
            "confirmationIndicateOffline": false,
            "integerValue": false,
            "onValue": "on",
            "offValue": "off",
            "minColorTemperature": 2700,
            "maxColorTemperature": 6500,
            "accessory": "mqttthing"
        }
