### ISSUE TITLE
zigbee2mqtt and xiaomi door sensor

### ISSUE THREAD

**Issue by dezral** [arachnetech/homebridge-mqttthing#100] opened 2019-04-25 20:18 UTC
im using this config..

```
 {   
     "accessory": "mqttthing",
     "type": "occupancySensor",
     "name": "Bagdøren",
     "url": "http://127.0.0.1:1883",
     "topics":
     {   
         "getOccupancyDetected": { 
         "topic": "zigbee2mqtt/0x00158e5202e6be17",
         "apply": "return JSON.parse(message).contact;"
     }
 },
     "onValue": false,
     "offValue": true
 }
```

the output is an json that looks like this

`{"contact":true,"linkquality":110,"battery":100,"voltage":3015}`

homekit see the sensor but, don't get any change in homekit..

status is true when the door is closed, and false when open!

what im i missing?

**Comment by dezral** [comment] 2019-04-27 12:23
fixet with:

{
    "accessory": "mqttthing",
    "type": "contactSensor",
    "name": "door",
    "url": "http://127.0.0.1:1883",
    "topics":
    {
        "getContactSensorState": { 
        "topic": "zigbee2mqtt/0x00158gr002f6be17",
        "apply": "return( ( JSON.parse(message).contact == false ) ? 1 : null || ( JSON.parse(message).contact == true ) ? 0  : null);"
        },

        "getBatteryLevel": { 
        "topic": "zigbee2mqtt/0x00158gr002f6be17",
        "apply": "return JSON.parse(message).battery;"
        }

},
    "integerValue": true
}

but i don't understand why that mqttting can't parse the json object "contact"

**Comment by odx** [comment] 2019-05-02 04:28
This is what I use for my Xiaomi sensors:

```
{
            "accessory": "mqttthing",
            "username": "username",
            "password": "password",
            "type": "contactSensor",
            "history": true,
            "name": "Door1",
            "topics": {
                "getContactSensorState": {
                    "topic": "zigbee/door1",
                    "apply": "return !(JSON.parse(message).contact);"
                },
                "getStatusLowBattery": {
                    "topic": "zigbee/door1",
                    "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
                },
                "getBatteryLevel": {
                    "topic": "zigbee/door1",
                    "apply": "return JSON.parse(message).battery;"
                }
            },
            "integerValue": true
        }
```

**Comment by viperet** [comment] 2019-07-23 21:29
Had the same problem...
Thanks, @odx your config works perfectly! Should be added to the https://github.com/arachnetech/homebridge-mqttthing/wiki/Tested-Configurations

**Comment by jdtsmith** [comment] 2020-03-04 03:46
The problem is `mqttthing` expects the _strings_ `"true"` and `"false"`, not the bare JS boolean tokens which zigbee2mqtt puts in its MQTT payloads.  See #218.

**Comment by arachnetech** [comment] 2020-04-05 16:02
Closing as JS true/false now accepted.

**Closed by arachnetech** 2020-04-05 16:02 UTC
