### ISSUE TITLE
turnOffAfterms for Garage Door

### ISSUE THREAD

**Issue by WEZANGO** [arachnetech/homebridge-mqttthing#180] opened 2019-12-15 00:58 UTC
My garage door has only 1 button to open the garage and doesn't have a button to close it. So every time I open the door through homekit it stays in opening state and I have to close it to open again. Is it possible to turnOffAfterms, so it's state would automatically turn to closed?

**Comment by arachnetech** [comment] 2020-04-13 23:36
Closing this one as duplicate of #127.

**Closed by arachnetech** 2020-04-13 23:36 UTC
