### ISSUE TITLE
Thermostat

### ISSUE THREAD

**Issue by andreyxc** [arachnetech/homebridge-mqttthing#476] opened 2021-09-22 18:17 UTC
After reboot, it forgets the values, it is possible to remember the old value ON OFF :(

**Comment by arachnetech** [comment] 2021-09-25 16:26
Not currently, unfortunately. Requested and on my list.
Closing this issue, as effectively a duplicate of #245.

**Closed by arachnetech** 2021-09-25 16:26 UTC

**Comment by rbswift** [comment] 2021-09-26 11:43
Two options are to make the status topic retained then whenever homebridge restarts it will subscribe to the topic and receive  the retained value. Alternatively, you can use `startPub` message to request the current status whenever homebridge restarts (e.g. from Tasmota with something like a `cmnd/mylight/power` message)
